
import streamlit as st
st.set_page_config(page_title="QuLab: Risk-Adjusted Return (RARORAC) Calculator", layout="wide")

# Initialize session state variables
if 'saved_scenarios' not in st.session_state:
    st.session_state.saved_scenarios = {}
if 'current_rarorac_params' not in st.session_state:
    st.session_state.current_rarorac_params = {}
if 'current_rarorac_results' not in st.session_state:
    st.session_state.current_rarorac_results = {}

st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("QuLab: Risk-Adjusted Return (RARORAC) Calculator")
st.divider()

page = st.sidebar.selectbox(label="Navigation", options=["RARORAC Calculator & Scenarios", "Portfolio Quality Visualization"])

if page == "RARORAC Calculator & Scenarios":
    from application_pages.page1 import run_page1
    run_page1()
elif page == "Portfolio Quality Visualization":
    from application_pages.page3 import run_page3
    run_page3()

st.markdown("---")
st.subheader("References")
st.markdown(r"""
[15] Chapter 3: The Risk Management Framework, 'Risk Pricing' subsection.  
[16] Chapter 3: The Risk Management Framework, 'Components of Determining Risk Pricing' subsection.  
[17] Chapter 3: The Risk Management Framework, 'The Denominator' subsection.  
[18] Chapter 3: The Risk Management Framework, 'Risk Insensitive Pricing and Client / Counterparty Behavior' and 'Risk Sensitive Pricing' subsections, referencing Figure 4: Portfolio Quality Distribution.
""")


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@qusandbox.com](mailto:info@qusandbox.com)
''')
